-- Schema PARCIAL de despachos (likida-ai-enterprise), generado con 'alembic upgrade head --sql'.
-- Cubre SOLO las migraciones 0001 y 0002 (DDL puro). La migración 0003_seed.py hace un
-- INSERT ... RETURNING y lee el valor de vuelta para usarlo en inserts siguientes -- eso
-- requiere una conexión real a Postgres, no se puede volcar como SQL offline.
-- Cuando se cree el proyecto unificado, correr las migraciones de despachos con:
--   cd despachos && B2B_DB_URL=postgresql://... python3 -m alembic upgrade head
-- (esto SÍ ejecuta 0003+ correctamente, conectado de verdad).

CREATE SCHEMA IF NOT EXISTS despachos;
SET search_path TO despachos, public;

BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0001_initial

CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    name TEXT NOT NULL, 
    rfc TEXT, 
    blocked BIGINT DEFAULT '0', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    name TEXT NOT NULL, 
    email TEXT, 
    role TEXT DEFAULT 'contador', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    folio_fiscal TEXT, 
    archivo TEXT NOT NULL, 
    fecha TEXT, 
    tipo TEXT, 
    serie TEXT, 
    folio TEXT, 
    emisor_rfc TEXT, 
    emisor_nombre TEXT, 
    receptor_rfc TEXT, 
    subtotal TEXT, 
    iva TEXT, 
    total TEXT, 
    moneda TEXT DEFAULT 'MXN', 
    descripcion TEXT, 
    categoria TEXT, 
    confianza FLOAT, 
    razon_clasificacion TEXT, 
    valido BIGINT DEFAULT '0', 
    requires_human_review BIGINT DEFAULT '1', 
    issues TEXT, 
    erp_poliza TEXT, 
    erp_status TEXT, 
    status TEXT DEFAULT 'procesado', 
    procesado_en TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_invoices_tenant_folio UNIQUE (tenant_id, folio_fiscal), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    invoice_id BIGINT NOT NULL, 
    tenant_id BIGINT NOT NULL, 
    categoria TEXT, 
    confianza FLOAT, 
    razon TEXT, 
    method TEXT DEFAULT 'rules', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    FOREIGN KEY(invoice_id) REFERENCES invoices (id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    tool_name TEXT NOT NULL, 
    action TEXT, 
    entity TEXT, 
    entity_id TEXT, 
    payload TEXT, 
    status TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    type TEXT NOT NULL, 
    channel TEXT NOT NULL, 
    recipient TEXT, 
    subject TEXT, 
    body TEXT, 
    status TEXT DEFAULT 'queued', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id)
);

CREATE TABLE schema_version (
    version BIGSERIAL NOT NULL, 
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (version)
);

CREATE TABLE api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    name TEXT NOT NULL, 
    key_hash TEXT NOT NULL, 
    active BIGINT DEFAULT '1', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_api_keys_hash UNIQUE (key_hash), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    nombre TEXT NOT NULL, 
    despacho TEXT, 
    email TEXT NOT NULL, 
    facturas TEXT, 
    mensaje TEXT, 
    status TEXT DEFAULT 'nuevo', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id)
);

CREATE TABLE tenant_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    config_key TEXT NOT NULL, 
    config_value TEXT, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_tenant_config UNIQUE (tenant_id, config_key), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    invoice_id BIGINT, 
    reason TEXT, 
    decision TEXT, 
    status TEXT DEFAULT 'pending', 
    notes TEXT, 
    resolved_by TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    resolved_at TIMESTAMP WITH TIME ZONE, 
    PRIMARY KEY (id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
    FOREIGN KEY(invoice_id) REFERENCES invoices (id)
);

CREATE TABLE webhook_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    event TEXT, 
    url TEXT, 
    payload TEXT, 
    attempts BIGINT DEFAULT '0', 
    max_attempts BIGINT DEFAULT '3', 
    last_status TEXT, 
    last_error TEXT, 
    next_retry_at TIMESTAMP WITH TIME ZONE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    completed_at TIMESTAMP WITH TIME ZONE, 
    PRIMARY KEY (id)
);

CREATE TABLE collection_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    factura_id TEXT NOT NULL, 
    tipo_recordatorio TEXT NOT NULL, 
    canal TEXT DEFAULT 'email', 
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    respuesta TEXT, 
    PRIMARY KEY (id)
);

CREATE TABLE outstanding_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT, 
    factura_id TEXT NOT NULL, 
    monto FLOAT NOT NULL, 
    fecha_vencimiento TEXT NOT NULL, 
    dias_vencido BIGINT DEFAULT '0', 
    score FLOAT DEFAULT '0.0', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_outstanding_unique UNIQUE (tenant_id, factura_id)
);

CREATE UNIQUE INDEX idx_outstanding_unique ON outstanding_invoices (tenant_id, factura_id);

CREATE TABLE tenant_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    api_calls BIGINT DEFAULT '0', 
    invoices_processed BIGINT DEFAULT '0', 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_tenant_usage UNIQUE (tenant_id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE webhook_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    event TEXT NOT NULL, 
    url TEXT NOT NULL, 
    active BIGINT DEFAULT '1', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_wh_subscription UNIQUE (tenant_id, event, url), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE cuentas_contables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    codigo TEXT NOT NULL, 
    descripcion TEXT NOT NULL, 
    nivel BIGINT DEFAULT '3', 
    naturaleza TEXT DEFAULT 'D', 
    grupo TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_cuenta_tenant UNIQUE (tenant_id, codigo), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE asientos_contables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    fecha TEXT NOT NULL, 
    cuenta_debito TEXT NOT NULL, 
    cuenta_credito TEXT NOT NULL, 
    monto TEXT NOT NULL, 
    descripcion TEXT, 
    factura_id TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE balanzas_mensuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    periodo TEXT NOT NULL, 
    cuenta_id BIGINT, 
    saldo_inicial TEXT DEFAULT '0.00', 
    debe TEXT DEFAULT '0.00', 
    haber TEXT DEFAULT '0.00', 
    saldo_final TEXT DEFAULT '0.00', 
    PRIMARY KEY (id), 
    CONSTRAINT uq_balanza UNIQUE (tenant_id, periodo, cuenta_id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
    FOREIGN KEY(cuenta_id) REFERENCES cuentas_contables (id)
);

CREATE TABLE paquetes_contabilidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    periodo TEXT NOT NULL, 
    rfc TEXT, 
    estado TEXT DEFAULT 'borrador', 
    payload TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE client_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    tenant_id BIGINT NOT NULL, 
    email TEXT NOT NULL, 
    password_hash TEXT NOT NULL, 
    name TEXT, 
    role TEXT DEFAULT 'cliente', 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_client_user UNIQUE (tenant_id, email), 
    FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE TABLE portal_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
    token_hash TEXT NOT NULL, 
    user_id BIGINT NOT NULL, 
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
    PRIMARY KEY (id), 
    CONSTRAINT uq_portal_token UNIQUE (token_hash), 
    FOREIGN KEY(user_id) REFERENCES client_users (id)
);

INSERT INTO alembic_version (version_num) VALUES ('0001_initial') RETURNING alembic_version.version_num;

-- Running upgrade 0001_initial -> 0002_indexes
